version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: js-yaml
    versions:
    - 3.14.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@types/node"
    versions:
    - 14.0.14
  - dependency-name: handlebars
    versions:
    - 4.7.6
